// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmB9lpKWH9XCTJapF5oX5RCjvFlEDTO3U',
    appId: '1:965476473190:web:10b9e4b8f75eb8b46ed0a7',
    messagingSenderId: '965476473190',
    projectId: 'aplikasicatatankuliah-a2bec',
    authDomain: 'aplikasicatatankuliah-a2bec.firebaseapp.com',
    databaseURL: 'https://aplikasicatatankuliah-a2bec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah-a2bec.firebasestorage.app',
    measurementId: 'G-3HCXK2D9FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXYw9PDBzymBO24aUhBIBvExcdSL6h8AQ',
    appId: '1:965476473190:android:b07ac241789f98a16ed0a7',
    messagingSenderId: '965476473190',
    projectId: 'aplikasicatatankuliah-a2bec',
    databaseURL: 'https://aplikasicatatankuliah-a2bec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah-a2bec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP1yFA0BWEkUOlkJUgmQ0kBEhKsqnhggc',
    appId: '1:965476473190:ios:f8afe060eaa33c5f6ed0a7',
    messagingSenderId: '965476473190',
    projectId: 'aplikasicatatankuliah-a2bec',
    databaseURL: 'https://aplikasicatatankuliah-a2bec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah-a2bec.firebasestorage.app',
    iosBundleId: 'com.example.aplikasicatatankuliah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP1yFA0BWEkUOlkJUgmQ0kBEhKsqnhggc',
    appId: '1:965476473190:ios:f8afe060eaa33c5f6ed0a7',
    messagingSenderId: '965476473190',
    projectId: 'aplikasicatatankuliah-a2bec',
    databaseURL: 'https://aplikasicatatankuliah-a2bec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah-a2bec.firebasestorage.app',
    iosBundleId: 'com.example.aplikasicatatankuliah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmB9lpKWH9XCTJapF5oX5RCjvFlEDTO3U',
    appId: '1:965476473190:web:a0ee1ce2da572bfe6ed0a7',
    messagingSenderId: '965476473190',
    projectId: 'aplikasicatatankuliah-a2bec',
    authDomain: 'aplikasicatatankuliah-a2bec.firebaseapp.com',
    databaseURL: 'https://aplikasicatatankuliah-a2bec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah-a2bec.firebasestorage.app',
    measurementId: 'G-T793ML7ZSN',
  );
}
